### ISSUE TITLE
Unpacking error when cache hits

### ISSUE THREAD

**Issue by alirezatheh** [tecolicom/actions-use-homebrew-tools#2]
@kaz-utashiro hi,
```
tar: Error exit delayed from previous errors.
```

**Comment by kaz-utashiro** [comment]
I can't tell what is happening from this message.
Workflow file and result would be helpful.

**Comment by kaz-utashiro** [comment]
I experienced the same error recently in:
https://github.com/tecoli-com/actions-use-perl-tools/actions/runs/3349237955/jobs/5549058005

This may be the similar situation as in:
https://github.com/msys2/MSYS2-packages/issues/1216

I still can't tell if this is the case of you from your report.

**Comment by kaz-utashiro** [comment]
Above problem was solved by adding -P option for tar when extracting.
I close this issue.
