### ISSUE TITLE
Add cache-from and cache-to options

### ISSUE THREAD

**Issue by Xpl0itU** [tecolicom/actions-use-homebrew-tools#3]
I have a workflow that gets triggered whenever I create a tag, however, the created cache only works for that tag, and not other tags or any other run at all, see this SO post for what I mean: https://stackoverflow.com/questions/74113734/share-gha-docker-cache-among-branches

**Comment by kaz-utashiro** [comment]
The article is about docker action and I am not sure how it relates to this action.

From my experience, the cache mechanism seems to be working regardless of the tag.
https://github.com/kaz-utashiro/greple-jq/actions

If you can show me the history of the action that is actually not working, I may be able to provide more details.

**Comment by Xpl0itU** [comment]
Here's my workflow https://github.com/Xpl0itU/WiiUDownloader/blob/main/.github/workflows/macos.yml, inter-tags caching isn't working for me: https://github.com/Xpl0itU/WiiUDownloader/actions/runs/8741312805/job/23987045220

**Comment by kaz-utashiro** [comment]
I found a statement in https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache.

> Workflow runs also cannot restore caches created for different tag names.

So it seems to be an intended restriction of actions/cache.
There are some discussions.

https://github.com/actions/cache/issues/1175
